#Mount NetApp NFS Mount
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /media/netappfiles
        state: directory
        mode: '0755'


    - name: Mount an NFS volume
      ansible.posix.mount:
        src: 172.16.209.200:/netappfiles
        path: /media/netappfiles
        opts: rw,sync,hard,intr
        state: mounted
        fstype: nfs
