- hosts: localhost
  gather_facts: false
  vars:
    login: &login
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  vars_files: /root/ONTAPvars.yml
  tasks:

    - name: Install NetApp simulator Licenses
      na_ontap_cluster:
        state: present
        cluster_name: "{{ clustername }}"
        license_code: "{{ item }}"
        <<: *login
      loop:
        - CAYHXPKBFDUFZGABGAAAAAAAAAAA
        - APTLYPKBFDUFZGABGAAAAAAAAAAA
        - WSKTAQKBFDUFZGABGAAAAAAAAAAA
        - CGVTEQKBFDUFZGABGAAAAAAAAAAA
        - OUVWXPKBFDUFZGABGAAAAAAAAAAA
        - QFATWPKBFDUFZGABGAAAAAAAAAAA
        - UHGXBQKBFDUFZGABGAAAAAAAAAAA
        - GCEMCQKBFDUFZGABGAAAAAAAAAAA
        - KYMEAQKBFDUFZGABGAAAAAAAAAAA
        - SWBBDQKBFDUFZGABGAAAAAAAAAAA
        - YDPPZPKBFDUFZGABGAAAAAAAAAAA
        - INIIBQKBFDUFZGABGAAAAAAAAAAA
        - EJFDVRRRYVHXCFABGAAAAAAAAAAA
        - UZLKTRRRYVHXCFABGAAAAAAAAAAA
        - OSYVWRRRYVHXCFABGAAAAAAAAAAA
        - GUJZTRRRYVHXCFABGAAAAAAAAAAA
        - CYAHWRRRYVHXCFABGAAAAAAAAAAA
        - QDDSVRRRYVHXCFABGAAAAAAAAAAA
        - MBXNQRRRYVHXCFABGAAAAAAAAAAA
        - YBCNLUNFXMSMUCEZFAAAAAAAAAAA

    - name: Set NTP
      na_ontap_ntp:
        state: present
        version: auto
        server_name: "{{ ntpservers }}"
        <<: *login

    - name: Set Timezone
      na_ontap_command:
        command: ['cluster', 'date', 'modify', '-timezone', 'America/New_York']
        privilege: admin
        <<: *login

    - name: Assign unowned disks
      na_ontap_disks:
        node: "{{ clustername }}"
        <<: *login

    - name: Create Aggregates and wait 5 minutes until aggregate is online
      na_ontap_aggregate:
        state: present
        service_state: online
        name: aggr1
        disk_count: 14
        wait_for_online: True
        time_out: 300
        <<: *login

    - name: Create SVM
      na_ontap_svm:
        state: present
        name: "{{ vserver }}"
        root_volume: vserver_root
        root_volume_aggregate: aggr1
        root_volume_security_style: unix
        <<: *login
  
    - name: Create Additional Volume within Vserver
      na_ontap_volume:
        state: present
        name: minio_vol
        vserver: "{{ vserver }}"
        aggregate_name: aggr1
        size: 2
        size_unit: gb
        policy: default
        junction_path: "/minio_vol"
        percent_snapshot_space: 0
        space_guarantee: none
        volume_security_style: unix
        wait_for_completion: true
        <<: *login
 
    - name: Create NFS Export Rule Under Default Policy
      na_ontap_export_policy_rule:
        state: present
        name: default
        vserver: "{{ vserver }}"
        client_match: 172.16.209.0/24
        ro_rule: any
        rw_rule: any
        protocol: nfs
        super_user_security: any
        <<: *login

    - name: Create interface
      na_ontap_interface:
       state: present
       interface_name: data
       home_port: e0c
       home_node: homecluster-01
       role: data
       protocols: nfs
       admin_status: up
       failover_policy: local-only
       firewall_policy: mgmt
       is_auto_revert: true
       address: 172.16.209.200
       netmask: 255.255.255.0
       force_subnet_association: false
       vserver: "{{ vserver }}"
       <<: *login

    - name: Start NFS
      na_ontap_nfs:
        state: present
        service_state: started
        vserver: "{{ vserver }}"
        nfsv3: enabled
        <<: *login
